import { test, expect } from "@playwright/test";
import { installDesktopMock } from "./desktop.mock";
import { CITY_TEST_FILENAME, importCityFixture } from "./data-fixtures";

test("MCP controls, snapshot isolation and generated layers keep source intact", async ({ page }) => {
  await installDesktopMock(page);
  await page.goto("/");
  await importCityFixture(page);
  await expect.poll(() => page.evaluate(() => window.__ZG_TEST__.calls.filter(c => c.command === "gis_workspace_sync").at(-1)?.args.layers)).toHaveLength(1);
  const snapshot = await page.evaluate(() => window.__ZG_TEST__.calls.filter(c => c.command === "gis_workspace_sync").at(-1)?.args);
  const source = (snapshot!.layers as { id: string; name: string; features: unknown[] }[])[0];
  expect(source.name).toBe(CITY_TEST_FILENAME);
  expect(source.features).toHaveLength(4);
  expect(JSON.stringify(snapshot)).not.toContain("connectionId");
  await page.getByRole("button", { name: "设置", exact: true }).click();
  await page.getByRole("button", { name: "MCP", exact: true }).click();
  await page.getByRole("button", { name: "启用 MCP", exact: true }).click();
  await expect(page.getByLabel("MCP 访问令牌")).toHaveAttribute("type", "password");
  await expect(page.getByRole("main", {name:"后台设置"})).toContainText("http://127.0.0.1:9999/mcp");
  await expect(page.getByRole("button", { name: "选择可读文件…", exact: true })).toHaveCount(0);
  await page.getByText("连接配置", {exact:true}).click();
  await expect(page.locator(".settings-disclosure[open] .settings-disclosure-content")).toContainText("Agent 负责授权");
  await page.getByRole("button", { name: "返回地图", exact: true }).click();
  await page.evaluate(() => window.__ZG_TEST__.analysisResults.push({ id: "result-1", name: "空间筛选结果", features: [{ type: "Feature", id: "selected", geometry: { type: "Point", coordinates: [116, 40] }, properties: { name: "结果" } }] }));
  await expect(page.locator(".layer-row")).toHaveCount(2);
  await expect(page.locator(".layer-text").filter({ hasText: "空间筛选结果" })).toContainText("*");
  await expect.poll(() => page.evaluate(() => window.__ZG_TEST__.calls.filter(c => c.command === "gis_workspace_sync").at(-1)?.args.layers)).toHaveLength(2);
  const final = await page.evaluate(() => window.__ZG_TEST__.calls.filter(c => c.command === "gis_workspace_sync").at(-1)?.args.layers as { features: unknown[] }[]);
  expect(final[0].features).toEqual(source.features);
  await page.getByRole("button", { name: "Codex Agent", exact: true }).click();
  await expect(page.getByLabel("Codex 空间分析助手")).toBeVisible();
  await page.getByTitle("隐藏侧栏，保留会话").click();
  await expect(page.getByLabel("Codex 空间分析助手")).toHaveCount(0);
});
