export type AnalysisGeometryKind = "point" | "line" | "polygon";
export type AnalysisParameter =
  "distanceMeters" | "toleranceMeters" | "groupBy" | "predicate";

export interface AnalysisTool {
  id: string;
  label: string;
  category: string;
  description: string;
  keywords: string[];
  requiresTarget: boolean;
  sourceKinds: AnalysisGeometryKind[];
  targetKinds?: AnalysisGeometryKind[];
  metric: boolean;
  parameters: AnalysisParameter[];
  help: string;
  report?: boolean;
}

export const analysisToolCategories = [
  "叠加分析",
  "空间关系",
  "几何处理",
  "质量与统计",
] as const;
const all: AnalysisGeometryKind[] = ["point", "line", "polygon"];
const polygons: AnalysisGeometryKind[] = ["polygon"];
const points: AnalysisGeometryKind[] = ["point"];

export const analysisTools: AnalysisTool[] = [
  {
    id: "buffer",
    label: "缓冲区",
    category: "叠加分析",
    description: "按距离生成要素周围的面。",
    keywords: ["buffer", "缓冲", "距离"],
    requiresTarget: false,
    sourceKinds: all,
    metric: true,
    parameters: ["distanceMeters"],
    help: "为每个输入要素生成缓冲面，保留其属性。正距离表示向外扩展；需要整体缓冲范围时，可对结果继续执行融合。",
  },
  {
    id: "clip",
    label: "裁剪",
    category: "叠加分析",
    description: "保留输入面位于目标面范围内的部分。",
    keywords: ["clip", "裁切", "掩膜"],
    requiresTarget: true,
    sourceKinds: polygons,
    targetKinds: polygons,
    metric: false,
    parameters: [],
    help: "输入与目标都须为面图层。目标面定义裁剪范围，结果保留输入属性，不修改原图层。",
  },
  {
    id: "intersection",
    label: "相交",
    category: "叠加分析",
    description: "提取两个面图层的共同部分。",
    keywords: ["intersection", "intersect", "交集"],
    requiresTarget: true,
    sourceKinds: polygons,
    targetKinds: polygons,
    metric: false,
    parameters: [],
    help: "将输入面与目标面逐一相交，输出共同覆盖的区域，并关联双方属性。",
  },
  {
    id: "difference",
    label: "差异",
    category: "叠加分析",
    description: "从输入面中扣除目标面覆盖的部分。",
    keywords: ["difference", "erase", "差集", "擦除"],
    requiresTarget: true,
    sourceKinds: polygons,
    targetKinds: polygons,
    metric: false,
    parameters: [],
    help: "输入与目标的顺序决定结果：保留输入面未被目标覆盖的区域，结果保留输入属性。",
  },
  {
    id: "symmetric_difference",
    label: "对称差异",
    category: "叠加分析",
    description: "提取两个面图层各自独有的区域。",
    keywords: ["symmetric difference", "xor", "对称差"],
    requiresTarget: true,
    sourceKinds: polygons,
    targetKinds: polygons,
    metric: false,
    parameters: [],
    help: "输出任一图层覆盖、但双方没有共同覆盖的部分，排除交集区域。",
  },
  {
    id: "dissolve",
    label: "融合",
    category: "叠加分析",
    description: "消除面之间的内部边界，可按字段分组。",
    keywords: ["dissolve", "union", "合并面", "溶解"],
    requiresTarget: false,
    sourceKinds: polygons,
    metric: false,
    parameters: ["groupBy"],
    help: "不选择字段时融合全部输入面；选择字段后，将相同字段值的面融合为一组。输入属性不会逐条保留，请使用分组字段识别结果。",
  },
  {
    id: "spatial_query",
    label: "按位置提取",
    category: "空间关系",
    description: "按与目标图层的空间关系提取输入要素。",
    keywords: [
      "spatial query",
      "extract by location",
      "位置查询",
      "空间查询",
      "选择",
    ],
    requiresTarget: true,
    sourceKinds: all,
    targetKinds: all,
    metric: false,
    parameters: ["predicate"],
    help: "关系方向为“输入要素相对于目标要素”。通常满足任一目标即可匹配；选择不相交时，输入须与全部目标不相交。结果保留输入属性。",
  },
  {
    id: "spatial_join",
    label: "按位置关联统计",
    category: "空间关系",
    description: "为输入要素记录空间匹配的目标数量和索引。",
    keywords: [
      "spatial join",
      "join attributes by location",
      "空间关联",
      "连接",
    ],
    requiresTarget: true,
    sourceKinds: all,
    targetKinds: all,
    metric: false,
    parameters: ["predicate"],
    help: "关系方向为“输入相对于目标”。保留输入几何与属性，附加匹配目标的数量和索引；未匹配输入也保留。本工具不复制目标图层的完整属性。",
  },
  {
    id: "nearest",
    label: "最近目标",
    category: "空间关系",
    description: "为每个输入要素寻找最近的目标。",
    keywords: ["nearest", "nearest neighbor", "最近邻", "距离"],
    requiresTarget: true,
    sourceKinds: all,
    targetKinds: all,
    metric: true,
    parameters: [],
    help: "按要素几何之间的最近距离寻找目标，附加目标索引与近似距离。相交或接触的要素距离为零。",
  },
  {
    id: "count_points",
    label: "面内点计数",
    category: "空间关系",
    description: "统计每个输入面包含的目标点数量。",
    keywords: ["count points in polygon", "点统计", "数量"],
    requiresTarget: true,
    sourceKinds: polygons,
    targetKinds: points,
    metric: false,
    parameters: [],
    help: "输入选择面图层，目标选择点图层。统计与面内部或边界相交的点，保留输入面并添加计数字段。",
  },
  {
    id: "centroid",
    label: "质心",
    category: "几何处理",
    description: "为每个输入要素计算几何中心。",
    keywords: ["centroid", "中心点", "重心"],
    requiresTarget: false,
    sourceKinds: all,
    metric: false,
    parameters: [],
    help: "生成每个要素的质心并保留属性。凹面或含洞的面，其质心可能位于面外；需要内部点时使用“面内点”。",
  },
  {
    id: "point_on_surface",
    label: "面内点",
    category: "几何处理",
    description: "为每个面生成一个位于面内部的点。",
    keywords: [
      "point on surface",
      "pointonsurface",
      "interior point",
      "内部点",
    ],
    requiresTarget: false,
    sourceKinds: polygons,
    metric: false,
    parameters: [],
    help: "生成位于面内部的代表点，适合放置标签或表示面对象。结果保留输入属性。",
  },
  {
    id: "convex_hull",
    label: "凸包",
    category: "几何处理",
    description: "生成包围每个输入要素的最小凸几何。",
    keywords: ["convex hull", "凸壳"],
    requiresTarget: false,
    sourceKinds: all,
    metric: false,
    parameters: [],
    help: "分别计算每个输入要素的凸包并保留属性。点或共线几何的凸包仍可能是点或线。",
  },
  {
    id: "envelope",
    label: "包络矩形",
    category: "几何处理",
    description: "生成每个要素与坐标轴对齐的边界框。",
    keywords: ["envelope", "bounding box", "bbox", "外接矩形", "范围"],
    requiresTarget: false,
    sourceKinds: all,
    metric: false,
    parameters: [],
    help: "为每个输入要素生成经纬度边界框，保留属性。退化为单点或共线范围时，结果可能为点或线。",
  },
  {
    id: "multipart_to_singleparts",
    label: "多部件转单部件",
    category: "几何处理",
    description: "将多点、多线、多面拆成独立要素。",
    keywords: ["multipart to singleparts", "explode", "拆分", "单部件"],
    requiresTarget: false,
    sourceKinds: all,
    metric: false,
    parameters: [],
    help: "每个部件生成一个要素并复制原属性。单部件直接保留；面的内环仍属于原面，不拆成独立面。",
  },
  {
    id: "extract_vertices",
    label: "提取顶点",
    category: "几何处理",
    description: "将输入要素的顶点输出为点图层。",
    keywords: ["extract vertices", "nodes", "节点", "顶点"],
    requiresTarget: false,
    sourceKinds: all,
    metric: false,
    parameters: [],
    help: "提取线、面和多部件的顶点并保留原要素属性，附加顶点、部件和环的索引以定位来源。",
  },
  {
    id: "polygon_to_lines",
    label: "面转线",
    category: "几何处理",
    description: "将面的外边界和内环转换为线。",
    keywords: ["polygon to lines", "boundary", "边界线", "轮廓"],
    requiresTarget: false,
    sourceKinds: polygons,
    metric: false,
    parameters: [],
    help: "提取面的外环和内环作为线几何，保留输入属性。相邻面的共享边界仍分别保留。",
  },
  {
    id: "simplify",
    label: "简化几何",
    category: "几何处理",
    description: "按米制容差减少线、面的顶点。",
    keywords: ["simplify", "douglas peucker", "抽稀", "简化"],
    requiresTarget: false,
    sourceKinds: ["line", "polygon"],
    metric: true,
    parameters: ["toleranceMeters"],
    help: "容差越大，保留的顶点通常越少。结果保留属性；不提供相邻要素共享边界的拓扑联动，请对结果执行拓扑检查。",
  },
  {
    id: "geometry_attributes",
    label: "添加几何属性",
    category: "几何处理",
    description: "添加近似长度、面积和周长等属性。",
    keywords: [
      "geometry attributes",
      "add geometry",
      "length",
      "area",
      "面积",
      "长度",
      "周长",
    ],
    requiresTarget: false,
    sourceKinds: all,
    metric: true,
    parameters: [],
    help: "保留输入几何与原属性，添加适用于其几何类型的度量字段。长度和周长单位为米，面积为平方米。",
  },
  {
    id: "merge",
    label: "合并图层",
    category: "几何处理",
    description: "把两个图层的要素汇集到独立图层。",
    keywords: ["merge vector layers", "append", "拼接", "合并"],
    requiresTarget: true,
    sourceKinds: all,
    targetKinds: all,
    metric: false,
    parameters: [],
    help: "合并两个输入图层的要素与属性字段，不消除重叠或内部边界。结果可包含不同几何类型；需要消除面边界时使用融合。",
  },
  {
    id: "topology_check",
    label: "拓扑检查",
    category: "质量与统计",
    description: "检查无效几何、重复几何及面重叠。",
    keywords: ["topology check", "validity", "拓扑", "有效性", "重复", "重叠"],
    requiresTarget: false,
    sourceKinds: all,
    metric: false,
    parameters: [],
    report: true,
    help: "返回问题清单，不自动修复数据。检查几何有效性、完全相同的几何和面之间的重叠；未覆盖面缝隙或共享边界一致性。要素序号按本次输入顺序显示。",
  },
  {
    id: "layer_summary",
    label: "图层摘要",
    category: "质量与统计",
    description: "查看要素数量、几何类型、字段和范围。",
    keywords: ["layer summary", "statistics", "摘要", "统计", "字段", "范围"],
    requiresTarget: false,
    sourceKinds: all,
    metric: false,
    parameters: [],
    report: true,
    help: "查看输入图层的几何与字段概况、经纬度范围。勾选仅使用选中要素时，摘要只统计本次选中的输入。",
  },
];

export function getAnalysisTool(id: string): AnalysisTool | undefined {
  return analysisTools.find((tool) => tool.id === id);
}
